- name: install packages with loops
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'redis' , state: 'absent' }
    - { name: 'zip' , state: 'present' }
    - { name: 'nginx' , state: 'absent' }
