- name: install packages with loops
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - redis
    - zip
    - nginx
